config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'

  root 'homepage#index'

  resources :categories
  resources :terms do
    collection do
      get 'error'
    end
  end

  # User
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  # Session
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :terms

  validates :name, presence: true, uniqueness: true
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :category

  validates :name, presence: true, uniqueness: true

  def self.search(search)
    where("name LIKE ? or definition LIKE ? ", "%#{search}%", "%#{search}%")
  end

  def user_authored_term?(user)
    author == user
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  # Returns a boolean representing if the user is logged in
  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  # Method to use in a filter to ensure the user is logged in
  def authorize!
    redirect_to login_path unless logged_in?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authorize!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :subject_area)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @terms = Term.order(created_at: :desc).take(5)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # logging in
  def new
  end

  # handle the post from the login page
  def create
    # Extract the email and password from the params
    email = params[:email]
    password = params[:password]

    # Find the user by their email
    user = User.find_by(email: email)

    # If we found a user and their password checks out
    if user && user.authenticate(password)
      # Save the user_id in the session cookie
      session[:user_id] = user.id

      # logged in!
      redirect_to root_path
    else
      # Nope, something went wrong
      redirect_to login_path
    end
  end

  # logout
  def destroy
    # Remove their user_id from the session
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]
  before_filter :authorize!

  # GET /terms
  # GET /terms.json
  def index
    if params[:search]
      @terms = Term.search(params[:search]).order(:name)
    else
      @terms = Term.all.order(:name)
    end
  end

  # Want to have GET /terms/error
  def error
    render :permission_error
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
  end

  # GET /terms/new
  def new
    @term = Term.new
    @categories = Category.all
  end

  # GET /terms/1/edit
  def edit
    unless Term.find(params[:id]).user_authored_term?(current_user.name)
      redirect_to error_terms_path
    end

    @categories = Category.all
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(term_params)

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render :show, status: :created, location: @term }
      else
        format.html { render :new }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terms/1
  # PATCH/PUT /terms/1.json
  def update
    unless Term.find(params[:id]).user_authored_term?(current_user.name)
      redirect_to error_terms_path
    end

    respond_to do |format|
      if @term.update(term_params)
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { render :show, status: :ok, location: @term }
      else
        format.html { render :edit }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    unless Term.find(params[:id]).user_authored_term?(current_user.name)
      redirect_to error_terms_path
    end

    @term.destroy
    respond_to do |format|
      format.html { redirect_to terms_url, notice: 'Term was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_term
    @term = Term.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def term_params
    params.require(:term).permit(:name, :definition, :author, :web_link, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to signup_path
    end
  end
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :subject_area
    = f.text_field :subject_area
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %thead
    %tr
      %th Name
      %th Subject area
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= category.subject_area
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Subject area:
  = @category.subject_area

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/homepage/index.html.haml
.container-fluid
  .row.homepage-gallery
    .col-sm-5
      %h1.text-right
        Welcome
        -if logged_in?
          = current_user.name
    .col-sm-7.recent-terms
      %h3 Recently Added
      %ul.list-unstyled
        - @terms.each do |term|
          %li
            = link_to "#{term.name}", term_path(term.id), class: "btn btn-default"
            = term.definition

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TIY Glossary
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if logged_in?
      %nav.navbar.navbar-default.navbar-fixed-top
        .container-fluid
          / Brand and toggle get grouped for better mobile display
          .navbar-header
            %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => "/"} TIY Glossary
          / Collect the nav links, forms, and other content for toggling
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li.active
                = link_to 'Terms', terms_path
              %li
                = link_to 'Categories', categories_path

            %form.navbar-form.navbar-right{ action: "/terms" }
              .form-group
                -# %input.form-control{:placeholder => "Search Terms", :type => "text", :name => "search" }/
                = text_field_tag :search, params[:search]

              %button.btn.btn-default{:type => "submit"} Submit
            %ul.nav.navbar-nav.navbar-right
              %li.dropdown
                %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  = current_user.name
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to "Logout", logout_path
                  %li.divider{:role => "seperator"}
                  %li= link_to "New Term", new_term_path
                  %li.divider{:role => "separator"}
                  %li= link_to "New Category", new_category_path
          / /.navbar-collapse
        / /.container-fluid
    - else
      %nav.navbar.navbar-default.navbar-fixed-top
        .container-fluid
          / Brand and toggle get grouped for better mobile display
          .navbar-header
            %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => "/"} TIY Glossary
          / Collect the nav links, forms, and other content for toggling
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li.active
                = link_to 'Login', login_path
              %li
                = link_to 'Sign up', signup_path
    .row
      .col-md-12
        = yield

app/views/session/new.html.haml
.col-sm-offset-2.col-sm-8
  = form_tag login_path, { class: "form-horizontal" } do
    .form-group
      %h1.col-sm-2
        Login
    .form-group
      %label.col-sm-2.control-label
        Email:
      .col-sm-10
        = text_field_tag :email
    .form-group
      %label.col-sm-2.control-label
        Password:
      .col-sm-10
        = password_field_tag :password
    .form-group
      .col-sm-offset-2.col-sm-10
        = submit_tag "Submit", class: "btn btn-primary"

app/views/terms/_form.html.haml
= form_for @term, html: { class: "form-horizontal" }  do |f|
  - if @term.errors.any?
    #error_explanation
      %h2 = "#{pluralize(@term.errors.count, "error")} prohibited this term from being saved:"
      %ul
        - @term.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :author, value: current_user.name
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name
  .form-group
    = f.label :definition, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :definition
  .form-group
    = f.label :web_link, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :web_link
  .form-group
    .col-sm-10.col-sm-offset-2
      - @categories.each do |category|
        = f.label category.name, class: "control-label"
        = f.radio_button(:category_id, "#{category.id}")
  .actions.form-group
    .col-sm-offset-2
      = f.submit 'Save', class: "btn btn-primary"

app/views/terms/edit.html.haml
%h1 Editing term

= render 'form'

= link_to 'Show', @term
\|
= link_to 'Back', terms_path

app/views/terms/index.html.haml
%h1 Listing terms

%table
  %thead
    %tr
      %th Name
      %th Definition
      %th Author
      %th Web link
      %th Category
      %th
      %th
      %th

  %tbody
    - if @terms.any?
      - @terms.each do |term|
        %tr
          %td= term.name
          %td= term.definition
          %td= term.author
          %td= term.web_link
          %td= term.category_id
          %td= link_to 'Show', term
          - if current_user.name == term.author
            %td= link_to 'Edit', edit_term_path(term)
            %td= link_to 'Destroy', term, :method => :delete, :data => { :confirm => 'Are you sure?' }
    - else
      %p Nothing found
%br

= link_to 'New Term', new_term_path

app/views/terms/new.html.haml
%h1.center-text New Term

.container-fluid
  .row
    = render 'form'

app/views/terms/permission_error.html.haml
%h1 Only a term's author may modify it

app/views/terms/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @term.name
%p
  %b Definition:
  = @term.definition
%p
  %b Author:
  = @term.author
%p
  %b Web link:
  = @term.web_link
%p
  %b Category:
  = @term.category.name

- if current_user.name == @term.author
  = link_to 'Edit', edit_term_path(@term)
  \|
= link_to 'Back', terms_path

app/views/users/new.html.haml
%h1 Signup
%ul
  = form_for(@user) do |f|
    %li
      Name:
      = f.text_field :name
    %li
      Email:
      = f.text_field :email
    %li
      Password:
      = f.password_field :password
    %li
      Password Confirmation:
      = f.password_field :password
    %li
      = f.submit "Submit"